### ISSUE TITLE
changedAt needs to be updatedAt

### ISSUE THREAD

**Issue by flacoman91** [mimani/mongoose-diff-history#10]
Hello,

changedAt is not returning anything because it's being saved in mongo as updatedAt

Thanks.

**Comment by mimani** [comment]
HI Richard,

Can you please elaborate on this.

Thanks,
Saurabh Mimani

**Comment by flacoman91** [comment]
Sorry, i have a pr out for this. 


In mongo the value is being saved as updatedAt in the histories table.

**Comment by mimani** [comment]
Yes, was reviewing that, We can use createdAt as well there, what should it be?
