### ISSUE TITLE
Include user to history

### ISSUE THREAD

**Issue by yanlyan** [mimani/mongoose-diff-history#14]
How to include user to the history ?
I have user object in req.user object how to include that to history ?

**Comment by mimani** [comment]
Hello Lyan,

Thanks for exploring mongoose-diff-history.
You can refer this part of test code [here](https://github.com/mimani/mongoose-diff-history/blob/master/tests/diffHistory.js#L37).

Before saving the object, You just have to add an attribute: `__user` and assign the user object to it, like below:

                sampleV1 = sample2.toObject();
                sample2.def = "laer";
                sample2.__user = "Mimani";
                sample2.__reason = "to test it";
                sample2.save(function (err, sample3) {
                        ......
                        ......
                })

Let me know if you have any further queries.

**Comment by yanlyan** [comment]
Great, thanks a lot

**Comment by leonardoad** [comment]
That's great!
It could be on the documentation, tho
https://www.npmjs.com/package/mongoose-diff-history there is no mention of how to add the user to the object!
thanks!
