### ISSUE TITLE
Saving subdocuments even when they are not updated

### ISSUE THREAD

**Issue by capaci** [mimani/mongoose-diff-history#23]
I was searching some method to store history my data, so I found your plugin and i like the approach you take. 

However, when I update some document that has an array of subdocuments attached to it, this array is also stored in the `histories` collection, even no change has occured to the subdocuments.

I've read #15 , but it's not my case, since no data is changed in my subdocuments array.

Let me explain how it works. 
I have a collection for projects and for each project, a users array that contains objects that represent the role and permissions of a user within the project. My document is something like:

```json
{
	"_id" : ObjectId("5a8f35ca37e1fd04963a29ec"),
	"users" : [
		{
			"user" : ObjectId("5a8f35c937e1fd04963a29d6"),
			"role" : "Owner",
			"_id" : ObjectId("5a8f35ca37e1fd04963a29ed"),
			"permissions" : [
				"members_edit",
				"members_remove",
				"project_edit"
			],
			"createdAt" : ISODate("2018-02-26T18:25:57.088Z"),
			"updatedAt" : ISODate("2018-02-26T18:25:57.088Z")
		},
		{
			"updatedAt" : ISODate("2018-02-26T18:28:37.901Z"),
			"createdAt" : ISODate("2018-02-26T18:26:22.645Z"),
			"user" : ObjectId("5a8f35c937e1fd04963a29d5"),
			"role" : "Manager",
			"_id" : ObjectId("5a94514e29010702bf37145d"),
			"permissions" : [
				"project_edit"
			]
		}
	],
	"description" : "Some cool description",
	"name" : "Project #1",
	"__v" : 0,
	"createdAt" : ISODate("2018-02-26T18:23:17.659Z"),
	"updatedAt" : ISODate("2018-02-26T19:18:04.416Z")
}
```

And when I update the description, for example, the document in the `histories` collection is:

```json
{
	"_id" : ObjectId("5a945d6cb817aa035e9eec18"),
	"updatedAt" : ISODate("2018-02-26T19:18:04.428Z"),
	"createdAt" : ISODate("2018-02-26T19:18:04.428Z"),
	"collectionId" : ObjectId("5a8f35ca37e1fd04963a29ec"),
	"collectionName" : "Project",
	"diff" : {
		"description" : [
			"Some cool description",
			"Another cool description"
		],
		"users" : [
			[
				{
					"permissions" : [
						"members_edit",
						"members_remove",
						"project_edit"
					],
					"createdAt" : "2018-02-26T18:25:57.088Z",
					"_id" : "5a8f35ca37e1fd04963a29ed",
					"role" : "Owner",
					"user" : "5a8f35c937e1fd04963a29d6"
				},
				{
					"permissions" : [
						"project_edit"
					],
					"_id" : "5a94514e29010702bf37145d",
					"role" : "Manager",
					"user" : "5a8f35c937e1fd04963a29d5",
					"createdAt" : "2018-02-26T18:26:22.645Z"
				}
			],
			0,
			0
		]
	},
	"user" : ObjectId("5a8f35c937e1fd04963a29d6"),
	"version" : 0,
	"__v" : 0

```

My model and controller is as it follows:

```javascript
/* model.js */
const mongoose = require('mongoose')
const diffHistory = require('mongoose-diff-history/diffHistory')

const ProjectUserSchema = mongoose.Schema({
  user: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  role: { type: String, trim: true },
  permissions: [String]
},
{
  timestamps: true
})

const ProjectSchema = mongoose.Schema({
  name: { type: String },
  description: { type: String },
  users: [ ProjetUserSchema ]
},
{
  usePushEach: true,
  timestamps: true
})

ProjectSchema.plugin(diffHistory.plugin, { omit: ['updatedAt', 'users.updatedAt'] });
module.exports = mongoose.model('Project', ProjectSchema)
```

```javascript
/* controller.js */

...

const updateProject = (req, res, next) => {
  Project.findOne({ _id: req.params.id }, '-users', (err, project) => {
    if (err) return next(err)
    /* check if user can edit the project */
    if (userHasPermission(project, req.user, 'project_edit')) {
      for (let attribute in req.body) {
          project[attribute] = req.body[attribute]
      }
      project.__user = req.user._id
      project.save(err => {
        if (err) return next(err)
        res.json({ error: false, project_id: project._id })
      })
    } else {
      res.status(403).json({ message: 'Forbidden' }) // user is forbidden
    }
  })
}
...
```

Please, could you take a look to check what I'm doing wrong?

Also, note that I pass the field `updatedAt` to the plugin to omit. When I use [mongoose timestamps](http://mongoosejs.com/docs/guide.html#timestamps), the `updatedAt` always is updated and put in `histories` collection. Is there some way to ignore `updatedAt` field natively in the plugin?

**Comment by mimani** [comment]
Hey, Thanks for using this library and reporting it.

Which version of this library you are using? 

This library internally uses jsondiffpatch, which does not makes change in array of objects if it is not changed, as you can see it's demo here. But if your issue persists, I will check it over the weekend.

Also, regarding your query on updatedAt,  if you check the "diff" variable in histories, which actually stores the diff, does not have updatedAt, which means, it is not capturing updatedAt changes.

**Comment by majoraze** [comment]
I'm having the same issue here, even when I start the array of subdocuments empty and update another field that doesn't add subdocuments it still stores the array empty on diff.

**Comment by capaci** [comment]
Hi, @mimani and @majoraze, I'm using version 1.3.0 of the library.

I think I found the error. I was filtering the `users` property on my query.

```javascript
  Project.findOne({ _id: req.params.id }, '-users', (err, project) => {
    ...
  }
```

Then I simple remove this filter, and it worked as expected.
```javascript
  Project.findOne({ _id: req.params.id }, (err, project) => {
    ...
  }
```

And @mimani, as I said, in this example, the `updatedAt` field is not in histories because I was omiting it with the plugin configurations:

```javascript
ProjectSchema.plugin(diffHistory.plugin, { omit: ['updatedAt', 'users.updatedAt'] });
```

If I remove this config, the field is stored in histories every time.


Thanks for your attention!

**Comment by mimani-s** [comment]
@capaci Yes, you have to add `updatedAt` in the omit fields so that it can be ignored, if you dont want to save it in histories, The plugin inherently does not ignore any fields unless explicitly specified as you did.

I am not very clear about your first case where you say array still gets saved in diff, is this issue still happening?

**Comment by mimani-s** [comment]
@capaci Yes, you have to add updatedAt in the omit fields so that it can be ignored, if you dont want to save it in histories, The plugin inherently does not ignore any fields unless explicitly specified as you did.

I am not very clear about your first case where you say array still gets saved in diff, is this issue still happening?

**Comment by mimani** [comment]
@capaci Yes, you have to add updatedAt in the omit fields so that it can be ignored, if you dont want to save it in histories, The plugin inherently does not ignore any fields unless explicitly specified as you did.

I am not very clear about your first case where you say array still gets saved in diff, is this issue still happening?

**Comment by zjr** [comment]
@capaci, I am also trying to understand your issue, especially with regards to `updatedAt`. Is there a possibility that there is some confusion somewhere between `history.updatedAt` & `history.diff.users.x.updatedAt`? It looks like things are working as expected for you in the regard.

**Comment by zjr** [comment]
@capaci are you suggesting we that exclude the `updatedAt` field by default?
