### ISSUE TITLE
.updateOne is not working

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [mimani/mongoose-diff-history#28]
.update works like charm, however, my codebase is full of updateOne & updateMany.
I noticed .updateOne in the tests, but I can't seem to get it to work.

```
const diffHistory = require('mongoose-diff-history/diffHistory')

requestSchema = new Schema({...})

requestSchema.plugin(diffHistory.plugin);
```
That logs the difference
`await Request.update({ _id: request._id }, { isSwitched: true, switchedToRequestId: newRequest._id })`

But the following doesn't
`await Request.updateOne({ _id: request._id }, { isSwitched: true, switchedToRequestId: newRequest._id })`

**Comment by mimani** [comment]
You are right, `updateOne` was added recently but I forgot to push it to npm. I have just pushed it, You should be able to use it in the latest version of this library: 1.5.2

Sorry again for this, Thanks for using the library.
Let us know your feedback or any issue if you face.
Thanks

**Comment by AbdelrahmanHafez** [comment]
Thanks a lot, that did it.
