### ISSUE TITLE
Is updateMany or update with multi: true supported?

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [mimani/mongoose-diff-history#29]
Are either or both supported?

**Comment by ReggaePanda** [comment]
@AbdelrahmanHafez I think it works only if u use `$set`
```javascript
model.update({_id: XYZ}, {$set: { YOUR_UPDATE_OBJECT }}
```

**Comment by zjr** [comment]
Closing as stale, please reopen if you still have this question.

**Comment by AbdelrahmanHafez** [comment]
I don't use the plugin anymore, but IMO working just with $set bad DX since mongoose adds `$set` internally.
