### ISSUE TITLE
What about deletion?

### ISSUE THREAD

**Issue by pkalkman** [mimani/mongoose-diff-history#3]
Hi,

Great library, works fantastic!!!

Any plans to support deletion (removal) of documents in the near future?

Regards,
Peter Kalkman

**Comment by mimani** [comment]
Hey,

Thanks for checking it out. Are you planning to use it?

I have made changes to support different versions(https://github.com/mimani/mongoose-diff-history/pull/2), which I will release soon.

Can you elaborate more on what behaviour you are expecting on removal?

Thanks,
Saurabh Mimani

**Comment by pkalkman** [comment]
Hi Saurabh,

Yes, I'm currently evaluating the library for using it in my new project. So far I'm very positive :)

What I want by deletion (removal) of a document is an extra record in de `Histories` table with the id of the deleted document, and the user and reason (`__user` and `__reason`) who triggered the deletion.

I want this because as it is now, I can get a full Audit Trail for a document for Create and Update, but Deletion is not part of the audit history. The only way to achieve this now is with soft-deletion (setting a deletion boolean).

Do you understand what I mean?

Regards,
Peter

**Comment by mimani** [comment]
Hi Peter,

Sure, I get it. I will push this feature soon, by this weekend, 28th Aug.

Thanks,
Saurabh Mimani

**Comment by pkalkman** [comment]
Hi Saurabh,

Thanks, awesome that you can do this so quickly.

I'm not totally certain, but I guess it would be a great benefit for the library if the user field in the History collection would be more than just a simple string. In a real world scenario you want to save more information about the user then just the username. For example a user object might look like:

```
{
  'username': 'peter',
  'fullname': 'Peter Kalkman',
  'email': 'peter.kalkman@elect-it.nl',
  'mobile': '06-11111111',
  'roles': [
    'ADMIN', 'USER'
  ]
}
```
Any thoughts on allowing an ANY schema for user?

Regards,
Peter Kalkman

**Comment by mimani** [comment]
Hi,

This might as well be useful, I will look into that.

I have started working on remove functionality(https://github.com/mimani/mongoose-diff-history/pull/4), I will relook at the code once and add sample in example directory, Than Release a new version for this.

Thanks,
Saurabh Mimani

**Comment by mimani** [comment]
Hi Peter, 

I have added support for remove in version : [1.0.1,](https://www.npmjs.com/package/mongoose-diff-history). Please check it out and let me know your views on it.

You can see a sample use in example [API](https://github.com/mimani/mongoose-diff-history/blob/master/example/routes/employees.js#L122), where  I have deleted an employee object and getting the version using [objectId](https://github.com/mimani/mongoose-diff-history/blob/master/example/routes/employees.js#L99).

Please raise one more issue for making user object generic, Will look into that as well.

Thanks
Saurabh Mimani

**Comment by pkalkman** [comment]
Saurabh,

Support for deletion works like charme!

Regards,
Peter
