### ISSUE TITLE
mongoose-dff-history doesn't work for 'create' or 'save' operation. It should log it into history table for save operation too.

### ISSUE THREAD

**Issue by vishalpatidar00789** [mimani/mongoose-diff-history#35]
mongoose-dff-history doesn't work for 'create' or 'save' operation. It should log it into history table for save operation too.

I think in diffHistory.js

schema.pre('save', function (next) {
        if (this.isNew) {
            console.log("---------in save-------");
            this.constructor
            .findOne({ _id: this._id })
            .then(original => saveDiffObject(this, original, this, opts))
            .then(() => next())
            .catch(next);
        }    
        return next();
    });

this would be the solution, it works for me.

Can we update it in the package so that in latest version it will be available or can we have some configuration option to enable history log for save/create operation too.

**Comment by kevtsi** [comment]
The current version tries to handle 'save', however, with EmbeddedDocument it fails with TypeError: this.constructor.findOne is not a function.

**Comment by kevtsi** [comment]
changing the line if (this.isNew) to if (this.isNew || !this.constructor.findOne) solves the problem for me

**Comment by mimani** [comment]
This should be fixed in latest version: 1.6, Kindly check.

**Comment by albina-sharkz** [comment]
not work
