### ISSUE TITLE
support for transaction

### ISSUE THREAD

**Issue by dhwpong** [mimani/mongoose-diff-history#38]
is it possible to allow the mongoose-history to be included in the a transaction https://mongoosejs.com/docs/transactions.html,
e.g. if the original changes to the document was aborted, the history will also be rollback (removed)

Looking at your code, it should be possible by passing __session to your code in diffHistory.js
the program just need to pass __session:session along with __user and __reason as option and pick up by your program and include the __session during save and made history part of the transaction.

> const saveDiffObject = (currentObject, original, updated, opts, metaData) => {
>     const { __user: user, __reason: reason, **__session: session** } = metaData || currentObject;
> .......
>     return History.findOne({ collectionId, collectionName })
>         .sort('-version')
>         .then(lastHistory => {
>             const history = new History({
>                 collectionId,
>                 collectionName,
>                 diff,
>                 user,
>                 reason,
>                 version: lastHistory ? lastHistory.version + 1 : 0
>             });
>             **if (session) {** 
>                **// console.log('history in transaction');**
>                **return history.save({ session });**
>             **}**
>             return history.save();
>         });
> };

**Comment by mimani** [comment]
@dhwpong you can go ahead and put a PR, We will review and release updated version. Thanks for your suggestion.

**Comment by mimani** [comment]
Thanks for your contribution, I have published new version with your changes, with those, You issue shall be resolved. 

Thanks for using this library and fixing the issue you faced. Kindly close the issue if this is resolved.

**Comment by dhwpong** [comment]
Verify working with 1.6.1
