### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: key $set must not start with '$'

### ISSUE THREAD

**Issue by travis5491811** [mimani/mongoose-diff-history#41]
I added this to an existing project and it throws the following error on save/update:
`UnhandledPromiseRejectionWarning: Error: key $set must not start with '$'`

```
npm install mongoose-diff-history -s

var mongoose = require('mongoose'),
    diffHistory = require('mongoose-diff-history/diffHistory'),
    schema = new mongoose.Schema({ ... });
    schema.plugin(diffHistory.plugin);
```

**Comment by RamprakashJ** [comment]
I am getting same error.

**Comment by RamprakashJ** [comment]
If your using {timestamps: true} in schema, then you might get this error while updating the document using findOneAndUpdate. I used this way to avoid this error Model.findOneAndUpdate(query, { $set: data }, { new: true, timestamps: false})

**Comment by rejeevd** [comment]
I also face the same issue. If I use timestamps: true, then findOneAndUpdate fails.
timestamps are is important for us. 
Is there a plan for fixing this?

**Comment by harikrishnakanchi** [comment]
Even I was facing same issue. I raised a [PR](https://github.com/mimani/mongoose-diff-history/pull/46) addressing this. Hopefully it will get merged.
