### ISSUE TITLE
queryObject.find(...).lean(...).cursor is not a function

### ISSUE THREAD

**Issue by chaudharykiran** [mimani/mongoose-diff-history#44]
I am using mongoose v4.3.4. When I want to update my model using `findOneAndUpdate`, I am continuously getting this error message. #error #question

**Comment by zjr** [comment]
I'm not sure there's enough information here to help you. Please provide more information or this issue may be closed. A test case would be ideal.

**Comment by chaudharykiran** [comment]
It's been long time. I even don't know now what the problem was?

**Comment by zjr** [comment]
Alright, thank you. Going to close this issue then.
