### ISSUE TITLE
Allow `ANY` schema for User

### ISSUE THREAD

**Issue by pkalkman** [mimani/mongoose-diff-history#6]
Hi Saurabh,

As it is now, `username` is a string in the History model. In a real world scenario you want to save more information about the user then just the username. For example a user object might look like:
```
{
  'username': 'peter',
  'fullname': 'Peter Kalkman',
  'email': 'peter.kalkman@elect-it.nl',
  'mobile': '06-11111111',
  'roles': [
    'ADMIN', 'USER'
  ]
}
```
Any thoughts on allowing an ANY schema for user?

**Comment by mimani** [comment]
Hi Peter,

This should be available in [v1.1.1](https://www.npmjs.com/package/mongoose-diff-history). Please check it out, Let me know in case of any issues.

Thanks,
Saurabh Mimani
