### ISSUE TITLE
New issue with omit dependency url

### ISSUE THREAD

**Issue by yossef-worthy** [mimani/mongoose-diff-history#72]
https://github.com/mimani/mongoose-diff-history/blob/80000e4245c4c8342f9893afd46151a26489c487/package.json#L23

You should change from git://github.com/ into https://github.com/, builds and github actions are failing
AS suggested here https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported

**Comment by vunhuanh** [comment]
Seconded, this issue is breaking all my builds and I'm using a fork of the repo in the meantime. It needs to be changed before March 15th when Github will make requirements permanent https://github.blog/2021-09-01-improving-git-protocol-security-github/#no-more-unauthenticated-git
